env:
  browser: true
  node: true
extends:
  - bayathy

parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true

rules:
  "import/no-unresolved": off
overrides:
  - files: "**/*.@(stories|test).tsx"
    rules:
      "@typescript-eslint/no-unused-vars": off
